Repository no-chris/chord-symbol, pull requests merged in 2023-02, with the labels that each got.

#598 Custom filter type improvements
  packages/chord-symbol-ultimateguitar/src/chordSymbolUltimateGuitar.js
  packages/chord-symbol/API.md
  packages/chord-symbol/src/typedefs.js
  packages/chord-symbol/types/index.d.ts
Labels: enhancement

#607 Render roman numeral symbol
  packages/chord-symbol-ultimateguitar/lib/chord-symbol-ultimateguitar.js
  packages/chord-symbol-ultimateguitar/lib/chord-symbol-ultimateguitar.js.map
  packages/chord-symbol/API.md
  packages/chord-symbol/SLOC
  packages/chord-symbol/lib/chord-symbol-esm.js
  packages/chord-symbol/lib/chord-symbol.js
  packages/chord-symbol/lib/chord-symbol.js.map
  packages/chord-symbol/src/dictionaries/allKeys.js
  packages/chord-symbol/src/dictionaries/degrees.js
  packages/chord-symbol/src/dictionaries/notes.js
  packages/chord-symbol/src/dictionaries/scales.js
  packages/chord-symbol/src/parser/chordParserFactory.js
  packages/chord-symbol/src/parser/filters/checkIntervalsConsistency.js
  packages/chord-symbol/src/parser/filters/formatNumeralSymbol.js
  packages/chord-symbol/src/parser/filters/nameIndividualChordNotes.js
  packages/chord-symbol/src/parser/filters/parseBase.js
  packages/chord-symbol/src/parser/filters/parseDescriptor.js
  packages/chord-symbol/src/renderer/chordRendererFactory.js
  packages/chord-symbol/src/renderer/filters/transpose.js
  packages/chord-symbol/src/typedefs.js
  packages/chord-symbol/tests/parser/chordParserFactory.spec.js
  packages/chord-symbol/tests/parser/filters/formatNumeralSymbol.spec.js
  packages/chord-symbol/tests/renderer/printer/raw.spec.js
  packages/chord-symbol/types/index.d.ts
Labels: enhancement

#608 fix error when roman degree is not in the mapping table
  packages/chord-symbol/src/parser/filters/formatNumeralSymbol.js
  packages/chord-symbol/tests/parser/filters/formatNumeralSymbol.spec.js
Labels: bug

#610 Allow parsing of +5 as #5 and -5 as b5
  packages/chord-symbol/src/parser/filters/getParsableDescriptor.js
  packages/chord-symbol/tests/allChordsAndVariants.spec.js
  packages/chord-symbol/tests/parser/filters/getParsableDescriptor.spec.js
Labels: bug

#613 Use unicode escape sequences
  packages/chord-symbol/SLOC
  packages/chord-symbol/lib/chord-symbol-esm.js
  packages/chord-symbol/lib/chord-symbol.js
  packages/chord-symbol/lib/chord-symbol.js.map
  packages/chord-symbol/src/dictionaries/degrees.js
  packages/chord-symbol/src/parser/filters/formatNumeralSymbol.js
Labels: bug

#615 change entry point to unbundled version
  packages/chord-symbol-ultimateguitar/package.json
  packages/chord-symbol/MIGRATION.md
  packages/chord-symbol/README.md
  packages/chord-symbol/package.json
Labels: breaking

#614 Add "b" and "#" variations to german notes
  packages/chord-symbol/src/dictionaries/notes.js
  packages/chord-symbol/tests/parser/filters/parseBase.spec.js
Labels: enhancement
